version: "3.7"
services:
    # image project
    laravel_8:
        build: 
            args: 
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - laravel-eti
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-eti

    postgres:
        build: docker/postgres
        environment:
            - POSTGRES_DB=medicos_db
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=123123
        networks:
            - laravel-eti
        ports:
            - 5432:5432

    # queue
    queue:
        build: 
            args: 
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        networks: 
            - laravel-eti

networks: 
    laravel-eti:
        driver: bridge